export const USER_ROLES = {
  CITIZEN: 'citizen',
  RESPONDER: 'responder',
  DISPATCHER: 'dispatcher',
  COMMANDER: 'commander',
  ADMIN: 'admin',
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const ROLE_PERMISSIONS: Record<UserRole, readonly string[]> = {
  citizen: ['report:create', 'report:read_own', 'incident:read_public'],
  responder: [
    'report:create',
    'report:read_own',
    'incident:read',
    'assignment:read_assigned',
    'assignment:update_status',
    'evidence:create',
    'route:read',
  ],
  dispatcher: [
    'report:create',
    'report:read',
    'report:verify',
    'incident:create',
    'incident:read',
    'incident:update',
    'assignment:create',
    'assignment:read',
    'assignment:update',
    'evidence:create',
    'evidence:read',
    'route:read',
    'route:update',
    'ai:recommendation:read',
    'ai:recommendation:approve',
  ],
  commander: [
    'report:create',
    'report:read',
    'report:verify',
    'incident:create',
    'incident:read',
    'incident:update',
    'incident:close',
    'incident:merge',
    'assignment:create',
    'assignment:read',
    'assignment:update',
    'evidence:create',
    'evidence:read',
    'route:read',
    'route:update',
    'resource:manage',
    'team:manage',
    'ai:recommendation:read',
    'ai:recommendation:approve',
    'ai:recommendation:override',
    'audit:read',
  ],
  admin: [
    '*',
  ],
};
